server:
  port: 8088
spring:
  redis:
    host: 192.168.101.65
    port: 6379
    username: "default"
    password: "redis"
    lettuce:
      pool:
        max-active: 8 #�������
        max-idle: 8 #����������
        min-idle: 0 #��С��������
        max-wait: 100 #���ӵȴ�ʱ��
#    测试

